nome = str(input('Digite um nome completo:')).strip()
print('Analisando seu nome...')
print('Seu nome maiusculo é {}'.format(nome.upper()))
print('Seu nome minusculo sera {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))